### ISSUE TITLE
win11ローカルでの学習について

### ISSUE THREAD

**Issue by kotaro5487** [laksjdjf/sd-trainer#10]
win11Anacondaのローカル環境で実行したところ、
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'
のエラーが出ます。
調べたところ、https://github.com/IBM/Project_CodeNet/issues/21

main.pyの
num_worksers=2の部分をnum_worksers=0に変更すれば解消するようです。
理屈もわかっておらず、ほかに影響がでるようなら申し訳ありません。
ご報告まで。

**Comment by laksjdjf** [comment]
報告ありがとうございます。

num_workersはデータの読み込みを並列で行うオプションなので、CPUの使えるスレッド数が足りないか、並列処理ができない環境だとエラーが起きるのかもしれません。

0にしても大して変わらなそうなので、ちょっと試してから変更します。

**Comment by koukei46124** [comment]
リンク先のgitによると、lamba特有の問題なのかもしれませんね。詳細は不明ですが…
当方は13700kなのでスレッド的には問題ない気がしますが、なにか並列処理と相性が悪い環境かもしれません。
ありがとうございます。

**Comment by laksjdjf** [comment]
お手数でなければこれに置き換えて試してもらえませんか？
https://github.com/laksjdjf/sd-trainer/blob/851319de1f11fea65f10a28ccef42ff60a8425ea/main.py


lambda関数の利用を回避してみたんですが。https://github.com/laksjdjf/sd-trainer/commit/851319de1f11fea65f10a28ccef42ff60a8425ea

**Comment by koukei46124** [comment]
大丈夫そうです！
後気になるのは、保存した物がどんどん上書きされるので、
save_n_epochsがあんまり意味ない…というか回収しないといけないことくらいでしょうか…
…あとマスクを別途画像で指定できたら助かる…

**Comment by laksjdjf** [comment]
ありがとうございます。
save_n_epochsは途中でトラブったとき1からやり直さなくてもいいようにするものです。実装は難しくはないんですがあまり設定項目を増やさない方針（建前）です。
マスクを画像で指定は・・・トレーニングコードとは独立でマスクをnumpy配列にして保存するコードを作ればできるっちゃできます。

**Comment by koukei46124** [comment]
なるほど…！
save_n_epochs了解です！

マスク画像の分離の方は、
…最近目の部分だけの学習をさせたかったので、学習用画像の上にレイヤー作って目の部分だけを黒く塗ってレイヤー部分だけを出力すればいい感じにマスクできそうだなと思ったもので…
もしも気が向けばお願いできたら嬉しいです…
