### ISSUE TITLE
No module named 'lora.pfg_imp'

### ISSUE THREAD

**Issue by nezuki-in-the-wall** [laksjdjf/sd-trainer#14]
コードを公開してくださり、ありがとうございます！
顔だけ学習できるとのことで、非常に魅力的な機能だと感じました。

Colab上で実行してみたところ、main.pyで学習を始めるところで以下のエラーが起こりました。
`Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from lora.pfg_imp import PFGNetwork
ModuleNotFoundError: No module named 'lora.pfg_imp'`
Githubでコードを見て見たのですが、lora/pfg_imp.pyが存在していないように見えます。
この問題はどうやって解決すればよいでしょうか？

**Comment by laksjdjf** [comment]
すみません、この前別のブランチで更新するつもりがmainで更新しちゃったせいで起きたエラーです。＾＾
lora/pfg_imp.pyを追加しておきました。

**Comment by nezuki-in-the-wall** [comment]
お早い対応、ありがとうございます！
